language: php
php:
  - '7.2'
  - nightly

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE realworld_test;'

script:
  - phpunit

services:
  - mysql

notifications:
  email:
    recipients:
      - mike@sunnytree.org
    on_success: always # default: change
    on_failure: always # default: always

after_success:
  curl --silent
  # URL TO STAGE SITE HERE # Staging site
